name: Tests

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.nodejs }}

    - run: npm ci
    - run: npm test
    - run: npm run build
